#!/bin/zsh

#====================
#=====VARIABLES======
#====================
THEME=""
WORKING_DIR=$HOME/.dotfiles/working/

#get parameters
while getopts "lt:w:" opt; do
	case "$opt" in
		l) 
			ls -1 $HOME/.dotfiles/themes/
			exit 0
			;;

		t) THEME="$OPTARG" ;;
		w) WALLPAPER="$OPTARG" ;;
		\?)
			echo "Nutzung: $0 [-t theme_name] [-w wallpaper_name] [-l]"
			exit 1
			;;
	esac
done

THEME_DIR=$HOME/.dotfiles/themes/$THEME
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"



#====================
#=====DEP CHECK======
#====================

#check if theme is specified
if [ -z "$THEME" ]; then
	echo "Bitte ein Theme angeben!";
	exit 1;
fi

#check if theme exists
if [ ! -d "$THEME_DIR" ]; then
	echo "Theme $THEME existiert nicht!";
	exit 1;
fi

#check if wallpaper was set and is accepted
if [ -z "$WALLPAPER" ]; then
	WALLPAPER="$THEME"
elif [ ! -f "$HOME/Pictures/.wallpaper/$WALLPAPER" ]; then
	echo "Wallpaper '$WALLPAPER' existiert nicht. Fallback zum Theme-Standard: $THEME"
	WALLPAPER="$THEME"
fi

#check if working dir exists
if [ ! -d "$WORKING_DIR" ]; then
	mkdir -p $HOME/.dotfiles/working/
fi

#check if config dir exists
if [ ! -d "$CONFIG_DIR" ]; then
	mkdir -p $CONFIG_DIR
fi







#wallpaper
ln -sfn $HOME/Pictures/.wallpaper/$WALLPAPER $HOME/Pictures/.wallpaper/wallpaper

#zsh
ln -sfn $THEME_DIR/zshrc $HOME/.zshrc

#normal programs
ln -sfn $THEME_DIR/dunst/ $XDG_CONFIG_HOME/
ln -sfn $THEME_DIR/fastfetch/ $XDG_CONFIG_HOME/
ln -sfn $THEME_DIR/fuzzel/ $XDG_CONFIG_HOME/
ln -sfn $THEME_DIR/kitty/ $XDG_CONFIG_HOME/
ln -sfn $THEME_DIR/niri/ $XDG_CONFIG_HOME/
ln -sfn $THEME_DIR/yazi/ $XDG_CONFIG_HOME/
