set nocompatible

filetype on
filetype plugin on
filetype indent on

syntax on
set number
set cursorline

set tabstop=3

set smartcase
set showmode
set hlsearch
set showmode

set wildmenu
set wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx


" -----SCRIPT----- {{{

" This will enable code folding.
" Use the marker method of folding.
augroup filetype_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END



" }}}

