[general]
mpris_enabled = true
theme = "dark"
plugins_enabled = true
plugins_dir = "/home/max/.config/rs-pug/plugins"
music_directories = ["~/Music/"]

[search]
limit = 20
source = "youtube"

[mpv]
socket = "/tmp/rs-pug.sock"

[keybinds]
next = "."
prev = ","
mute = "-"
repeat = "r"
shuffle = "z"
seek_back = "["
seek_forward = "]"

[lua]
allow-lua-ui-changes = false
