font='JetBrainsMono Nerd Font'
prompt="> "
placeholder=""
icon-theme=default
icons-enabled=yes
use-bold=no

[colors]
background=000000bb
text=cdd6f4aa
# message=657b83ff
prompt=cdd6f4ff
# placeholder=93a1a1ff
input=ffffffaa
match=faa768aa
selection=faa76833
selection-text=ffffffff
selection-match=faa768ff
# counter=93a1a1ff
border=faa768ee