font=''
prompt=""
placeholder=""
icon-theme=default
icons-enabled=yes
use-bold=no

[colors]
background=
text=
# message=657b83ff
prompt=
# placeholder=93a1a1ff
input=
match=
selection=
selection-text=
selection-match=
# counter=93a1a1ff
border=