[filetype]
rules = [
	{ mime = "image/*", fg = "#" },
	{ mime = "video/*", fg = "#" },
	{ mime = "audio/*", fg = "#" },
	{ mime = "inode/empty", fg = "" },
	{ mime = "text/plain", fg = "" },
	{ url = "*/", fg = "#" }
]
